In [ ]:
#Write a code to reverse a string.

txt = "Have a nice day"
txt[::-1]

'yad ecin a evaH'

In [ ]:
#Write a code to count the number of vowels in a string.

txt = "Have a nice day"
count = 0
for i in txt:
  if i in "aeiou":
    count += 1
print(count)

6

In [ ]:
#Write a code to check if a string is palindrome or not.

a = str(input("enter string" " "))
if a == a[::-1]:
  print("string is a palindrome")
else:
  print("not")

enter string maam
string is a palindrome

In [ ]:
#Write a code to check if two given strings are anagrams of each other.

txt1 = str(input("enter string 1 " " "))
txt2 = str(input("enter string 2 " " "))
if sorted(txt1) == sorted(txt2):
  print("strings are anagrams")
else:
  print("not")

enter string 1  god
enter string 2  dog
strings are anagrams

In [ ]:
#Write a code to find all occurrences of a given string within another string.

str1 = "i love cricket and i want to play cricket"
substring = "cricket"
count = str1.count(substring)
print(count)

2

In [ ]:
#Write a code to covert a string to uppercase or lowercase.

string = "Today is hot"
uppercase = string.upper()
lowercase = string.lower()

today is hot

In [ ]:
#Write the code to count number of words in a string.

string = "i love cooking"
len(string.split())

3

In [ ]:
#Write a code to concat strings without using + operator

str1 = "Welcome"
str2 = "home"
concat = "".join([str1,str2])

print(concat)

Welcomehome

In [ ]:
#Write a code to remove all the occurreces of a specific element from a list.

games_list = ['mario', 'contra', 'minecraft', 'candy crush', 'contra']
a = "contra"
while a in games_list :
  games_list.remove(a)
games_list

['mario', 'minecraft', 'candy crush']

In [ ]:
#Wrte a code to find 2nd largest int from the list of integers.

int_list = [24, 14, 58,9, 42]
a = sorted(int_list)
a[1]

14

In [ ]:
#Create a code to count the occurences of each element in a list and return a dictionary with element as keys and their counts as values.

list1 = [1, 2, 3, 4, 5, 2, 3, 2]
list2 = []
num = {}
count = list1.count(1)
count1 = list1.count(2)
count2 = list1.count(3)
count3 = list1.count(4)
count4 = list1.count(5)
list2.append(count)
list2.append(count1)
list2.append(count2)
list2.append(count3)
list2.append(count4)
for list1, list2 in zip(list1, list2):
  num[list1] = list2
print(num)

{1: 1, 2: 3, 3: 2, 4: 1, 5: 1}

In [ ]:
#Write a code to reverse the list without built in function.

list1 = ["pen", "paper", 1, 2]
list1[::-1]

[2, 1, 'paper', 'pen']

In [ ]:
#Implement a code to remove duplicates from a list while preserving the order.

list1 = [1 ,2, 3, 4, 5, 3, 1]
new_list = set(list1)
print (new_list)

{1, 2, 3, 4, 5}

In [ ]:
#Write a code to check if a given list is sorted(either asacending or descending) or not.

list1 = ["a", "d", "c", "t"]
asc = sorted(list1)
dsc = asc[:: -1]
if list1 == asc :
  print("ascending")
elif list1 == dsc :
  print("descending")
else:
  print("neither")

neither

In [ ]:
#Write a code to merge two sorted list into a single sorted list.

list1 = ["pen", "pencil", "paper"]
list2 = ["music", "movie", "games"]
final_list = sorted(list1)
final_list2 = sorted(list2)
print(final_list + final_list2)

['paper', 'pen', 'pencil', 'games', 'movie', 'music']

In [ ]:
#Implement a code to find the interaction point of two given lists.

list1 = [5, 10, 15, 20, 25]
list2 = [4, 8, 12, 16, 20]
interaction_point = set(list1) & set(list2)
print(interaction_point)

{20}

In [ ]:
#Create a code to find union of two lists without duplicates.

first_list = [1, 2, 2, 5]
second_list = [2, 5, 7, 9]

print( set( first_list + second_list ) )

{1, 2, 5, 7, 9}

In [ ]:
# Write a code to shuffle the given list randomly without built in functions.

import random
list1 = [1, 2, 3, 4, 5, 6]

n = len(list1)
for i in range(n):
    j = random.randint(0, n-1)
    a = list1.pop(j)
    list1.append(a)

print(list1)

[1, 2, 4, 6, 3, 5]

In [ ]:
# Write a code that takes two tuples as input and return a new tuple with common elements.

a = ("onion", "potato", "tomato", "chilli")
b = ("spinach", "potato", "peas", "chilli")
c = set(a) & set(b)
print(c)

{'chilli', 'potato'}

In [ ]:
#Create a code that prompts the user to enter two sets of integers separated by commas. Print intersection of two sets.

list1 = [int(x) for x in input("enter numbers seperated by comma: ").split(",")]
list2 = [int(y) for y in input("enter numbers seperated by comma: ").split(",")]
c = set(list1) & set(list2)
print(c)

enter numbers seperated by comma: 1,2,3,4,5
enter numbers seperated by comma: 2,4,6,8,10
{2, 4}

In [ ]:
#Write a code to concatinate two tuples. The function should take two tuples as input and return a new tuple cotaining elements from both.

a = [int(x) for x in input("enter numbers: ").split(",")]
b = [int(y) for y in input("enter numbers: ").split(",")]
c = a + b
d = tuple(c)
print(d)

enter numbers seperated by comma: 1,2,3
enter numbers seperated by comma: 4,5,6
(1, 2, 3, 4, 5, 6)

In [ ]:
#Develop a code that prompts the user to input two sets of strings . Then, print the elements that are present in first list but not in second.

a = set(input("enter first set of strings: ").split(","))
b = set(input("enter second set of strings: ").split(","))
c = set(a) - set(b)
print(c)

enter first set of strings: a,b,c,d
enter second set of strings: a,f,g,d
{'c', 'b'}

In [ ]:
#Develop a code that takes a tuple and an element as input. The function should return the max and min values.

a = tuple(int(x) for x in input("enter numbers: ").split(","))
b = sorted(a)
min = b[:1]
max = b[-1:]
print(min)
print(max)

enter numbers: 30,20,40,10
[10]
[40]

In [ ]:
#Create a code that defines 2 sets of integers. Then print intersection, difference and union of two sets.

set1 = set([1, 2, 3, 4, 5])
set2 = set([3, 4, 5, 6, 7])
intersection = set(set1) & set(set2)
diff = set(set1) - set(set2)
union = set1.union(set2)
print(intersection)
print(diff)
print(union)

{3, 4, 5}
{1, 2}
{1, 2, 3, 4, 5, 6, 7}

In [ ]:
#Write a code that prompts the user to enter 2 sets of strings. Print symmetric difference of the sets.

x = set(input("enter first set of strings: ").split(","))
y = set(input("enter second set of strings: ").split(","))
a = set(x)
b = set(y)
z = a.symmetric_difference(b)
print(z)

enter first set of strings: orange, potato, monkey
enter second set of strings: banana, potato, water
{' water', ' monkey', 'banana', 'orange'}

In [1]:
#Write a code that takes a list of words as input and returns a dictionary where the keys are unique words and the values are the frequencies of those words in the input list.

def word_frequency(words):
    frequency = {}
    for word in words:
        if word in frequency:
            frequency[word] += 1
        else:
            frequency[word] = 1
    return frequency

words_list = ["apple", "banana", "apple", "orange", "banana", "apple"]
print(word_frequency(words_list))

{'apple': 3, 'banana': 2, 'orange': 1}

In [9]:
#Write a code that takes two dictionaries as input and merges them into a single dictionary. If there are common keys, the values should be added together.
def merge_dicts(dict1, dict2):
    merged = dict1.copy()
    for key, value in dict2.items():
        if key in merged:
            merged[key] += value
        else:
            merged[key] = value
    return merged

# Test the function
dict1 = {"a": 1, "b": 2, "c": 3}
dict2 = {"b": 3, "c": 4, "d": 5}
print("Merged dictionaries:", merge_dicts(dict1, dict2))

Merged dictionaries: {'a': 1, 'b': 5, 'c': 7, 'd': 5}

In [11]:
#Write a code to access a value in a nested dictionary. The function should take the dictionary and a list of keys as input and return the corresponding value. If any of the keys do not exist in the dictionary, the function should return None.
def access_nested_dict(nested_dict, keys):
    for key in keys:
        if isinstance(nested_dict, dict) and key in nested_dict:
            nested_dict = nested_dict[key]
        else:
            return None
    return nested_dict

nested = {"a": {"b": {"c": 42}}}
print("Nested dict access:", access_nested_dict(nested, ["a", "b", "c"]))
print("Nested dict access (non-existent key):", access_nested_dict(nested, ["a", "b", "d"]))

Nested dict access: 42
Nested dict access (non-existent key): None

In [12]:
#Write a code that takes a dictionary as input and returns a sorted version of it based on the values. You can choose whether to sort in ascending or descending order.
def sort_dict_by_values(input_dict, descending=True):
    sorted_items = sorted(input_dict.items(), key=lambda x: x[1], reverse=descending)
    return dict(sorted_items)

unsorted = {"a": 3, "b": 1, "c": 2}
print("Sorted dict (descending):", sort_dict_by_values(unsorted))
print("Sorted dict (ascending):", sort_dict_by_values(unsorted, descending=False))

Sorted dict (descending): {'a': 3, 'c': 2, 'b': 1}
Sorted dict (ascending): {'b': 1, 'c': 2, 'a': 3}

In [14]:
#Write a code that inverts a dictionary, swapping keys and values. Ensure that the inverted dictionary correctly handles cases where multiple keys have the same value by storing the keys as a list in the inverted dictionary.
def invert_dict(input_dict):
    inverted = {}
    for k, v in input_dict.items():
        if v in inverted:
            if isinstance(inverted[v], list):
                inverted[v].append(k)
            else:
                inverted[v] = [inverted[v], k]
        else:
            inverted[v] = k
    return inverted

original = {"a": 1, "b": 2, "c": 7, "d": 3}
print("Inverted dict:", invert_dict(original))

Inverted dict: {1: 'a', 2: 'b', 7: 'c', 3: 'd'}